Play travis
Otus-DevOps-2019-08/alex-krt_infra pull request #2
Opened 2019-09-15 16:11 UTC by alex-krt

2019-09-15 19:30 UTC, mrgreyves requested changes
Здравствуйте!) Необходимо добавить описание к пр и в ридми =)

2019-09-15 19:54 UTC, alex-krt commented
> Здравствуйте!) Необходимо добавить описание к пр и в ридми =)
Здравствуйте, описание к пр - это в файл PULL_REQUEST_TEMPLATE.md или при пулл реквесте комментарий?

2019-09-15 20:23 UTC, mrgreyves commented
![image](https://user-images.githubusercontent.com/34331259/64927167-cd2e8d80-d80f-11e9-975d-30872fb7c6ee.png)
Вот сюда имею ввиду =)

2019-09-15 20:35 UTC, alex-krt commented
> ![image](https://user-images.githubusercontent.com/34331259/64927167-cd2e8d80-d80f-11e9-975d-30872fb7c6ee.png)
> Вот сюда имею ввиду =)

Добавил. И в редми написал)

2019-09-16 13:36 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув. В дальнейшем не забывайте добавлять описания в пр и оформлять ридми =)

2019-09-16 19:45 UTC, merged